INSERT INTO `api`.`address` (`street`, `city`, `zipcode`, `country`) VALUES ('Kulas Light', 'Gwenborough', '92998-3874','England');
INSERT INTO `api`.`address` (`street`, `city`, `zipcode`, `country`) VALUES ('Victor Plains', 'Wisokyburgh', '90566-7771','England');
INSERT INTO `api`.`address` (`street`, `city`, `zipcode`, `country`) VALUES ('Douglas Extension', 'McKenziehaven', '59590-4157','England');
INSERT INTO `api`.`address` (`street`, `city`, `zipcode`, `country`) VALUES ('Hoeger Mall', 'South Elvis', '53919-4257"','England');
INSERT INTO `api`.`address` (`street`, `city`, `zipcode`, `country`) VALUES ('Skiles Walks', 'Roscoeview', '33263','England');
INSERT INTO `api`.`address` (`street`, `city`, `zipcode`, `country`) VALUES ('Norberto Crossing', 'South Christy', '92998-3874','England');
INSERT INTO `api`.`address` (`street`, `city`, `zipcode`, `country`) VALUES ('Rex Trail', 'Howemouth', '58804-1099','England');
INSERT INTO `api`.`address` (`street`, `city`, `zipcode`, `country`) VALUES ('Ellsworth Summit', 'Aliyaview', '45169','England');
INSERT INTO `api`.`address` (`street`, `city`, `zipcode`, `country`) VALUES ('Dayna Park', 'Bartholomebury', '76495-3109','England');
INSERT INTO `api`.`address` (`street`, `city`, `zipcode`, `country`) VALUES ('Kattie Turnpike', 'Lebsackbury', '31428-2261','England');

INSERT INTO `api`.`users` (`name`, `username`, `password`, address_id) VALUES ('Leanne Graham', 'Bret', 'pwd', 1);
INSERT INTO `api`.`users` (`name`, `username`, `password`, address_id) VALUES ('Ervin Howell', 'Antonette', 'pwd',2);
INSERT INTO `api`.`users` (`name`, `username`, `password`, address_id) VALUES ('Clementine Bauch', 'Samantha', 'pwd',3);
INSERT INTO `api`.`users` (`name`, `username`, `password`, address_id) VALUES ('Patricia Lebsack', 'Karianne', 'pwd',4);
INSERT INTO `api`.`users` (`name`, `username`, `password`, address_id) VALUES ('Chelsey Dietrich', 'Kamren', 'pwd',5);
INSERT INTO `api`.`users` (`name`, `username`, `password`, address_id) VALUES ('Mrs. Dennis Schulist', 'Leopoldo_Corkery', 'pwd',6);
INSERT INTO `api`.`users` (`name`, `username`, `password`, address_id) VALUES ('Kurtis Weissnat', 'Elwyn.Skiles', 'pwd',7);
INSERT INTO `api`.`users` (`name`, `username`, `password`, address_id) VALUES ('Nicholas Runolfsdottir V', 'Maxime_Nienow', 'pwd',8);
INSERT INTO `api`.`users` (`name`, `username`, `password`, address_id) VALUES ('Glenna Reichert', 'Delphine', 'pwd',9);
INSERT INTO `api`.`users` (`name`, `username`, `password`, address_id) VALUES ('Clementina DuBuque', 'Moriah.Stanton', 'pwd',10);

INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('delectus aut autem', 0, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quis ut nam facilis et officia qui', 0, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('fugiat veniam minus', 0, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et porro tempora', 0, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('laboriosam mollitia et enim quasi adipisci quia provident illum', 0, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('qui ullam ratione quibusdam voluptatem quia omnis', 0, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo expedita consequatur quia in', 0, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('uo adipisci enim quam ut ab', 1, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae perspiciatis ipsa"', 0, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo est ratione doloremque quia maiores aut', 1, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('vero rerum temporibus dolor', 1, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et doloremque nulla', 1, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('repellendus sunt dolores architecto voluptatum', 1, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ab voluptatum amet voluptas', 0, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('accusamus eos facilis sint et aut voluptatem', 1, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quo laboriosam deleniti aut qui', 0, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('dolorum est consequatur ea mollitia in culpa', 0, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae ipsa aut voluptatibus pariatur dolor nihil', 1, 1);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ullam nobis libero sapiente ad optio sint', 1, 1);

INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('delectus aut autem', 0, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quis ut nam facilis et officia qui', 0, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('fugiat veniam minus', 0, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et porro tempora', 0, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('laboriosam mollitia et enim quasi adipisci quia provident illum', 0, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('qui ullam ratione quibusdam voluptatem quia omnis', 0, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo expedita consequatur quia in', 0, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('uo adipisci enim quam ut ab', 1, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae perspiciatis ipsa"', 0, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo est ratione doloremque quia maiores aut', 1, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('vero rerum temporibus dolor', 1, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et doloremque nulla', 1, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('repellendus sunt dolores architecto voluptatum', 1, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ab voluptatum amet voluptas', 0, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('accusamus eos facilis sint et aut voluptatem', 1, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quo laboriosam deleniti aut qui', 0, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('dolorum est consequatur ea mollitia in culpa', 0, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae ipsa aut voluptatibus pariatur dolor nihil', 1, 2);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ullam nobis libero sapiente ad optio sint', 1, 2);

INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('delectus aut autem', 0, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quis ut nam facilis et officia qui', 0, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('fugiat veniam minus', 0, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et porro tempora', 0, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('laboriosam mollitia et enim quasi adipisci quia provident illum', 0, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('qui ullam ratione quibusdam voluptatem quia omnis', 0, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo expedita consequatur quia in', 0, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('uo adipisci enim quam ut ab', 1, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae perspiciatis ipsa"', 0, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo est ratione doloremque quia maiores aut', 1, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('vero rerum temporibus dolor', 1, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et doloremque nulla', 1, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('repellendus sunt dolores architecto voluptatum', 1, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ab voluptatum amet voluptas', 0, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('accusamus eos facilis sint et aut voluptatem', 1, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quo laboriosam deleniti aut qui', 0, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('dolorum est consequatur ea mollitia in culpa', 0, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae ipsa aut voluptatibus pariatur dolor nihil', 1, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ullam nobis libero sapiente ad optio sint', 1, 3);

INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('delectus aut autem', 0, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quis ut nam facilis et officia qui', 0, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('fugiat veniam minus', 0, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et porro tempora', 0, 3);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('laboriosam mollitia et enim quasi adipisci quia provident illum', 0, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('qui ullam ratione quibusdam voluptatem quia omnis', 0, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo expedita consequatur quia in', 0, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('uo adipisci enim quam ut ab', 1, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae perspiciatis ipsa"', 0, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo est ratione doloremque quia maiores aut', 1, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('vero rerum temporibus dolor', 1, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et doloremque nulla', 1, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('repellendus sunt dolores architecto voluptatum', 1, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ab voluptatum amet voluptas', 0, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('accusamus eos facilis sint et aut voluptatem', 1, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quo laboriosam deleniti aut qui', 0, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('dolorum est consequatur ea mollitia in culpa', 0, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae ipsa aut voluptatibus pariatur dolor nihil', 1, 4);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ullam nobis libero sapiente ad optio sint', 1, 4);

INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('delectus aut autem', 0, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quis ut nam facilis et officia qui', 0, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('fugiat veniam minus', 0, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et porro tempora', 0, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('laboriosam mollitia et enim quasi adipisci quia provident illum', 0, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('qui ullam ratione quibusdam voluptatem quia omnis', 0, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo expedita consequatur quia in', 0, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('uo adipisci enim quam ut ab', 1, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae perspiciatis ipsa"', 0, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo est ratione doloremque quia maiores aut', 1, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('vero rerum temporibus dolor', 1, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et doloremque nulla', 1, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('repellendus sunt dolores architecto voluptatum', 1, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ab voluptatum amet voluptas', 0, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('accusamus eos facilis sint et aut voluptatem', 1, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quo laboriosam deleniti aut qui', 0, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('dolorum est consequatur ea mollitia in culpa', 0, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae ipsa aut voluptatibus pariatur dolor nihil', 1, 5);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ullam nobis libero sapiente ad optio sint', 1, 5);

INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('delectus aut autem', 0, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quis ut nam facilis et officia qui', 0, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('fugiat veniam minus', 0, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et porro tempora', 0, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('laboriosam mollitia et enim quasi adipisci quia provident illum', 0, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('qui ullam ratione quibusdam voluptatem quia omnis', 0, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo expedita consequatur quia in', 0, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('uo adipisci enim quam ut ab', 1, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae perspiciatis ipsa"', 0, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo est ratione doloremque quia maiores aut', 1, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('vero rerum temporibus dolor', 1, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et doloremque nulla', 1, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('repellendus sunt dolores architecto voluptatum', 1, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ab voluptatum amet voluptas', 0, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('accusamus eos facilis sint et aut voluptatem', 1, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quo laboriosam deleniti aut qui', 0, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('dolorum est consequatur ea mollitia in culpa', 0, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae ipsa aut voluptatibus pariatur dolor nihil', 1, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ullam nobis libero sapiente ad optio sint', 1, 6);

INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('delectus aut autem', 0, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quis ut nam facilis et officia qui', 0, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('fugiat veniam minus', 0, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et porro tempora', 0, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('laboriosam mollitia et enim quasi adipisci quia provident illum', 0, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('qui ullam ratione quibusdam voluptatem quia omnis', 0, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo expedita consequatur quia in', 0, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('uo adipisci enim quam ut ab', 1, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae perspiciatis ipsa"', 0, 6);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo est ratione doloremque quia maiores aut', 1, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('vero rerum temporibus dolor', 1, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et doloremque nulla', 1, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('repellendus sunt dolores architecto voluptatum', 1, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ab voluptatum amet voluptas', 0, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('accusamus eos facilis sint et aut voluptatem', 1, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quo laboriosam deleniti aut qui', 0, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('dolorum est consequatur ea mollitia in culpa', 0, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae ipsa aut voluptatibus pariatur dolor nihil', 1, 7);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ullam nobis libero sapiente ad optio sint', 1, 7);

INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('delectus aut autem', 0, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quis ut nam facilis et officia qui', 0, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('fugiat veniam minus', 0, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et porro tempora', 0, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('laboriosam mollitia et enim quasi adipisci quia provident illum', 0,8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('qui ullam ratione quibusdam voluptatem quia omnis', 0, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo expedita consequatur quia in', 0, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('uo adipisci enim quam ut ab', 1, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae perspiciatis ipsa"', 0, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo est ratione doloremque quia maiores aut', 1, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('vero rerum temporibus dolor', 1, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et doloremque nulla', 1, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('repellendus sunt dolores architecto voluptatum', 1, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ab voluptatum amet voluptas', 0, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('accusamus eos facilis sint et aut voluptatem', 1, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quo laboriosam deleniti aut qui', 0, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('dolorum est consequatur ea mollitia in culpa', 0, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae ipsa aut voluptatibus pariatur dolor nihil', 1, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ullam nobis libero sapiente ad optio sint', 1, 8);

INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('delectus aut autem', 0, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quis ut nam facilis et officia qui', 0, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('fugiat veniam minus', 0, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et porro tempora', 0, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('laboriosam mollitia et enim quasi adipisci quia provident illum', 0,9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('qui ullam ratione quibusdam voluptatem quia omnis', 0, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo expedita consequatur quia in', 0, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('uo adipisci enim quam ut ab', 1, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae perspiciatis ipsa"', 0, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo est ratione doloremque quia maiores aut', 1, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('vero rerum temporibus dolor', 1, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et doloremque nulla', 1, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('repellendus sunt dolores architecto voluptatum', 1, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ab voluptatum amet voluptas', 0, 8);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('accusamus eos facilis sint et aut voluptatem', 1, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quo laboriosam deleniti aut qui', 0, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('dolorum est consequatur ea mollitia in culpa', 0, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae ipsa aut voluptatibus pariatur dolor nihil', 1, 9);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ullam nobis libero sapiente ad optio sint', 1, 9);

INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('delectus aut autem', 0, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quis ut nam facilis et officia qui', 0, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('fugiat veniam minus', 0, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et porro tempora', 0, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('laboriosam mollitia et enim quasi adipisci quia provident illum', 0,10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('qui ullam ratione quibusdam voluptatem quia omnis', 0, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo expedita consequatur quia in', 0, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('uo adipisci enim quam ut ab', 1, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae perspiciatis ipsa"', 0, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('illo est ratione doloremque quia maiores aut', 1, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('vero rerum temporibus dolor', 1, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('et doloremque nulla', 1, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('repellendus sunt dolores architecto voluptatum', 1, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ab voluptatum amet voluptas', 0, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('accusamus eos facilis sint et aut voluptatem', 1, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('quo laboriosam deleniti aut qui', 0, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('dolorum est consequatur ea mollitia in culpa', 0, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('molestiae ipsa aut voluptatibus pariatur dolor nihil', 1, 10);
INSERT INTO `api`.`todos` (`title`, `completed`, `user_id`) VALUES ('ullam nobis libero sapiente ad optio sint', 1, 10);